spring:
  application:
    name: board


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple_board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12341234


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true      # JPA가 생성하는 SQL을 로그로 보여줌
        format_sql: true    # SQL 보기 좋게 포맷팅

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 604800000 # refresh (1000 * 60 * 60 * 24 * 7)

logging:
  level:
    org:
      springframework:
        security: TRACE